// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8OnKXJ9AtGZHRDCzGW_yo7PF_MCXGeZg',
    appId: '1:409072893137:web:6dc0ebb214acfcf69259f0',
    messagingSenderId: '409072893137',
    projectId: 'my-app-f393a',
    authDomain: 'my-app-f393a.firebaseapp.com',
    storageBucket: 'my-app-f393a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmhwynKwD_E91YtT_FYlrnBX82lAobilM',
    appId: '1:409072893137:android:9ea63e0756408a4d9259f0',
    messagingSenderId: '409072893137',
    projectId: 'my-app-f393a',
    storageBucket: 'my-app-f393a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Dj5GxCtneTz9Sm50J8FxjDQfnZ5IeL0',
    appId: '1:409072893137:ios:cf4a0d3b45bdc2189259f0',
    messagingSenderId: '409072893137',
    projectId: 'my-app-f393a',
    storageBucket: 'my-app-f393a.appspot.com',
    iosClientId: '409072893137-n7he49t644jqihq7ocmphn63do45aphb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Dj5GxCtneTz9Sm50J8FxjDQfnZ5IeL0',
    appId: '1:409072893137:ios:cf4a0d3b45bdc2189259f0',
    messagingSenderId: '409072893137',
    projectId: 'my-app-f393a',
    storageBucket: 'my-app-f393a.appspot.com',
    iosClientId: '409072893137-n7he49t644jqihq7ocmphn63do45aphb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
